# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build github.com/fluofoxxo/outrun
    - name: Identify (1/2)
      run: git config --global user.email totallyrealemail@gmail.com
    - name: Identify (2/2)
      run: git config --global user.name "Phlox - Actions Edition"
    - name: Upload (1/3)
      run: git init
    - name: Upload (2/3)
      run: git pull https://github.com/yophlox/outrun
    - name: Upload (3/3)
      run: git add outrun.exe -f
    - name: Commit Changes
      run: git commit -m OutrunBuild
    - name: Push Changes
      run: git push  
